### ISSUE TITLE
移除麦克风权限

### ISSUE THREAD

**Issue by zhihe-code** [DikeyKing/DKRecorder#5]
请问你能做到在不需要录音的情况下把麦克风权限给移除吗？我看到你特意加了个recordAudio来设置是否需要录音，但我设置了false还是会去申请麦克风权限， 我尝试抽离出音频相关的东西，结果失败了，最终保存到本地没成功。

**Comment by DikeyKing** [comment]
https://github.com/DikeyKing/DKRecorder/releases/tag/0.1.2

已移除多余的麦克风权限
